# Generated by Django 5.0.4 on 2024-04-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'get_latest_by': 'ID'},
        ),
    ]
