# Generated by Django 5.0.4 on 2024-04-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'get_latest_by': 'ID', 'ordering': [-1]},
        ),
    ]
